version: '3.0'

services:
  backend:
    image: activepieces/backend:0.2.10
    restart: always
    privileged: true
    ports:
      - 172.17.0.1:3456:3000
    depends_on:
      - postgres
      - redis
    environment:
      - AP_BACKEND_URL=${BASE_URL}:3456/api
      - AP_ENGINE_EXECUTABLE_PATH=dist/packages/engine/main.js
      - AP_FRONTEND_URL=${BASE_URL}:8080
      - AP_NODE_EXECUTABLE_PATH=/usr/local/bin/node
      - AP_POSTGRES_DATABASE=activepieces
      - AP_POSTGRES_HOST=postgres
      - AP_POSTGRES_PASSWORD=${ADMIN_PASSWORD}
      - AP_POSTGRES_PORT=5432
      - AP_POSTGRES_USERNAME=postgres
      - AP_REDIS_HOST=redis
      - AP_REDIS_PORT=6379
    entrypoint:
     - node
     - dist/packages/backend/main.js

  frontend:
    image: activepieces/frontend:0.2.5
    restart: always
    depends_on: [ backend ]
    ports:
      - 172.17.0.1:8284:80

  postgres:
    image: postgres:14.4
    restart: always
    environment:
      - POSTGRES_DB=activepieces
      - POSTGRES_PASSWORD=${ADMIN_PASSWORD}
      - POSTGRES_USER=postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.0.7
    restart: always
    volumes:
      - ./redis_data:/data
